### ISSUE TITLE
Can't able to use it with auto layout programmatically.

### ISSUE THREAD

**Issue by ghost** [varunpm1/VPMOTPView#3]
Library doesn't work when we are using it without storyboard.

**Comment by varunpm1** [comment]
[VPMOTPView.zip](https://github.com/varunpm1/VPMOTPView/files/1434337/VPMOTPView.zip)
Hi @satishbabariya2 ,

I can see that the library works fine without storyboard as well. I have attached a sample of the same. Could you please verify once if I got your concern right?

Thanks, Varun
