### ISSUE TITLE
Changing border color after initialised

### ISSUE THREAD

**Issue by artoymsd** [varunpm1/VPMOTPView#4]
Hello! I have a problem, please can you give me some advices?

I want to check the OTP and if it's wrong change Default Border Color to red, for example. But the method otpFieldDefaultBorderColor doesn't work after otpTextView.initalizeUI() has initialised. Is there any way to change border color?

Thank you!

**Comment by varunpm1** [comment]
Hi @artoymsd ,

That's a good question. The current version doesn't support the border color when in error state. I would be happy to modify the existing capability to provide you the needed support. Probably in a day or two. Let me know if you have any more queries.

Thank, Varun

**Comment by artoymsd** [comment]
Hello, @varunpm1 
Looking forward to your commit. Thank you for your help! 

Artem

**Comment by varunpm1** [comment]
Hi @artoymsd 

I have now added the support for error color for OTP field when invalid OTP is entered.

```otpFieldErrorBorderColor``` variable now tends to your requirement. It's an optional variable used to set the border when an error state is encountered.

You can pass true or false in the following delegate to indicate a valid or invalid OTP -

```func hasEnteredAllOTP(hasEntered: Bool) -> Bool```

Let me know if you need anything else. Closing the issue.

Thanks, Varun

**Comment by p-nicolaou** [comment]
@varunpm1 This implementation for invalid entry appearance seems like is not working (or broke).
Running this code `otpField?.layer.borderColor = (otpFieldErrorBorderColor ?? otpFieldEnteredBorderColor).cgColor` doesn't change the colour of the border (I am using **.underlinedBottom** for your reference).
Changing the code to below, it does the trick 
`otpField?.shapeLayer.strokeColor = (otpFieldErrorBorderColor ?? otpFieldEnteredBorderColor).cgColor`
