### ISSUE TITLE
Backspace doesn't work util all textFields will be filled

### ISSUE THREAD

**Issue by evgenmedia** [varunpm1/VPMOTPView#5]
Hello!
I have a problem with your class. The problem is that the backspace button doesn't work when you filled not all of the OTP TextFields. How can I fix this issue?

**Comment by varunpm1** [comment]
Hi @evgenmedia 

Yes, this was a known issue. I had completely forgot about fixing this issue.

Apple doesn't call ```shouldChangeCharacters``` delegate if there are no characters available in the field. 

I might have to do a workaround to tackle this issue. Let me try that. I'll keep you posted. Thanks for identifying.

Thanks, Varun

**Comment by varunpm1** [comment]
Hi @evgenmedia 

This issue is now fixed in v1.1.3 tag. Please do let me know if this still persists. Closing the issue.

Thanks, Varun
