### ISSUE TITLE
How to use bullets?

### ISSUE THREAD

**Issue by Sakshi584** [varunpm1/VPMOTPView#7]
I need to use bullets like passcodes. How can I use them?

**Comment by varunpm1** [comment]
Hi @Sakshi584 

Is this the UI you're looking for - https://github.com/varunpm1/VPMOTPView/blob/master/AppleFilled.png?

If not, could you explain more?

Thanks, Varun

**Comment by Sakshi584** [comment]
Yes.
How can I use this?

**Comment by varunpm1** [comment]
It can be generated by setting the following properties -

**otpFieldDisplayType** set it to **circular**
**otpFilledEntryDisplay** set it to **true**

There are other properties which can be used to customize even more, like size, color, spacing etc. I have added comments to each and every possible options.

Let me know if you need anything else.

**Comment by Sakshi584** [comment]
I used this. But this is not working. this is my code

        VMview.delegate = self
        VMview.otpFieldsCount = 4
        VMview.otpFieldSize = 20.0
        VMview.cursorColor = .darkGray
        VMview.otpFieldEnteredBorderColor = .gray
        VMview.otpFieldDefaultBorderColor = .gray
        VMview.otpFieldDisplayType = .circular
        VMview.otpFilledEntryDisplay = true

Do I need to set any color to fill those circles? Because when I enter digits it gets stored but that is not visible.
![screen shot 2018-07-09 at 3 27 36 pm](https://user-images.githubusercontent.com/33745817/42444002-a7b22c5c-838c-11e8-96e6-56d8d52bb440.png)

**Comment by varunpm1** [comment]
You're almost there. There are basically 4 colors that can be used -

**otpFieldDefaultBackgroundColor**
**otpFieldEnteredBackgroundColor**
**otpFieldDefaultBorderColor**
**otpFieldEnteredBorderColor**

The first 2 variables will be used for fill color when a text is not entered vs when a text is entered.
The next 2 variables will be used for border color when a text is not entered vs when a text is entered.

So you just have to use the first 2 variables. Let me know if you need anything else.

**Comment by Sakshi584** [comment]
otpFieldDefaultBackgroundColor
otpFieldEnteredBackgroundColor

Yeah. This worked. Thanks for the help.

**Comment by varunpm1** [comment]
Sure no problem. I'm closing this issue.
