### ISSUE TITLE
Move textField

### ISSUE THREAD

**Issue by ikbalpathan** [varunpm1/VPMOTPView#8]
how can i set When first textField is  nill then another textField is not enable to touch. current situation user can touch and input any textField. 

Like First textField is empty then second and onward TextField not enable.

**Comment by varunpm1** [comment]
The support is already present. Please use ```shouldAllowIntermediateEditing``` flag for that purpose.

**Comment by ikbalpathan** [comment]
when previous text field is empty than current text field should not be edited
![img_0696](https://user-images.githubusercontent.com/17999976/42800268-c240ab52-89b8-11e8-8485-d75e3f2ca834.jpg)

**Comment by varunpm1** [comment]
Yes, I understand. Use the variable **shouldAllowIntermediateEditing** and set it to false.

**Comment by ikbalpathan** [comment]
i already use this
view_OTP.shouldAllowIntermediateEditing = false
i already create video. if you have link then i send you.

**Comment by varunpm1** [comment]
Can you send me the screenshot of the otp initialization code?

**Comment by ikbalpathan** [comment]
```
view_OTP.otpFieldInputType = .numeric
        view_OTP.otpFieldsCount = 6
        view_OTP.otpFieldDefaultBorderColor = .gray
        view_OTP.otpFieldEnteredBorderColor = UIColor(red: CGFloat(253/255.0), green: CGFloat(237/255.0), blue: CGFloat(87/255.0), alpha: CGFloat(1.0))
        view_OTP.otpFieldBorderWidth = 4
        view_OTP.delegate = self
        self.navigationItem.backBarButtonItem = UIBarButtonItem(title: "", style: .plain, target: nil, action: nil)
        // Create the UI
        view_OTP.shouldAllowIntermediateEditing = false
        view_OTP.initalizeUI()
```

**Comment by varunpm1** [comment]
Hmm, good catch. The feature seems to be broken. I'll look into it.

**Comment by varunpm1** [comment]
I have fixed the issue. Please update the code. Let me know if you need anything else. I'm closing this issue now.

**Comment by ikbalpathan** [comment]
Thanks a lot!
